-- MySQL Script generated by MySQL Workbench
-- 11/18/14 22:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema go2row
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema go2row
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `go2row` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `go2row` ;

-- -----------------------------------------------------
-- Table `go2row`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go2row`.`kategorie` (
  `kategorie_id` INT NOT NULL AUTO_INCREMENT,
  `kategorie` INT NULL,
  PRIMARY KEY (`kategorie_id`),
  UNIQUE INDEX `kategorie_id_UNIQUE` (`kategorie_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `go2row`.`mitglied`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go2row`.`mitglied` (
  `mitglied_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `vorname` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  `strasse` VARCHAR(45) NULL,
  `plz` INT NULL,
  `ort` VARCHAR(45) NULL,
  `kategorie_kategorie_id` INT NOT NULL,
  PRIMARY KEY (`mitglied_id`, `kategorie_kategorie_id`),
  INDEX `fk_mitglied_kategorie1_idx` (`kategorie_kategorie_id` ASC),
  UNIQUE INDEX `mitglied_id_UNIQUE` (`mitglied_id` ASC),
  CONSTRAINT `fk_mitglied_kategorie1`
    FOREIGN KEY (`kategorie_kategorie_id`)
    REFERENCES `go2row`.`kategorie` (`kategorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `go2row`.`boot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go2row`.`boot` (
  `boot_id` INT NOT NULL AUTO_INCREMENT,
  `b_name` VARCHAR(45) NULL,
  `kategorie_kategorie_id` INT NOT NULL,
  `schaden` TINYINT(1) NULL,
  PRIMARY KEY (`boot_id`),
  INDEX `fk_boot_kategorie1_idx` (`kategorie_kategorie_id` ASC),
  UNIQUE INDEX `boot_id_UNIQUE` (`boot_id` ASC),
  CONSTRAINT `fk_boot_kategorie1`
    FOREIGN KEY (`kategorie_kategorie_id`)
    REFERENCES `go2row`.`kategorie` (`kategorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `go2row`.`m_ausfahrt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go2row`.`m_ausfahrt` (
  `m_ausfahrt_id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NULL,
  `mitglied_id` INT NOT NULL,
  `steuermann` VARCHAR(45) NULL,
  `km` FLOAT NULL,
  `ruderziel` VARCHAR(45) NULL,
  `abfahrt` DATETIME NULL,
  `ankunft` DATETIME NULL,
  `bemerkung` LONGTEXT NULL,
  `boot_boot_id` INT NOT NULL,
  PRIMARY KEY (`m_ausfahrt_id`),
  INDEX `fk_m_ausfahrt_boot1_idx` (`boot_boot_id` ASC),
  UNIQUE INDEX `m_ausfahrt_id_UNIQUE` (`m_ausfahrt_id` ASC),
  CONSTRAINT `fk_m_ausfahrt_boot1`
    FOREIGN KEY (`boot_boot_id`)
    REFERENCES `go2row`.`boot` (`boot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `go2row`.`mitglied_has_m_ausfahrt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go2row`.`mitglied_has_m_ausfahrt` (
  `mitglied_mitglied_id` INT NOT NULL,
  `m_ausfahrt_m_ausfahrt_id` INT NOT NULL,
  PRIMARY KEY (`mitglied_mitglied_id`, `m_ausfahrt_m_ausfahrt_id`),
  INDEX `fk_mitglied_has_m_ausfahrt_m_ausfahrt1_idx` (`m_ausfahrt_m_ausfahrt_id` ASC),
  INDEX `fk_mitglied_has_m_ausfahrt_mitglied1_idx` (`mitglied_mitglied_id` ASC),
  CONSTRAINT `fk_mitglied_has_m_ausfahrt_mitglied1`
    FOREIGN KEY (`mitglied_mitglied_id`)
    REFERENCES `go2row`.`mitglied` (`mitglied_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mitglied_has_m_ausfahrt_m_ausfahrt1`
    FOREIGN KEY (`m_ausfahrt_m_ausfahrt_id`)
    REFERENCES `go2row`.`m_ausfahrt` (`m_ausfahrt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
